"""M8C-A identity, authorization, and future-audit contracts."""

from decision_agent.security.audit import (
    AuditAction,
    AuditChainError,
    AuditComponent,
    AuditEvent,
    AuditEventType,
    AuditOutcome,
    JsonlAuditSink,
    new_audit_event,
)
from decision_agent.security.governance import (
    AuditSink,
    GovernedChatCompletionClient,
    GovernedNativeToolCallingModel,
    GovernedProviderRole,
    InMemoryAuditSink,
    ProviderGovernance,
)
from decision_agent.security.models import (
    AuthenticationMethod,
    DataScope,
    KnowledgeScope,
    PrincipalType,
    RequestPrincipal,
    SecurityAuthorizationError,
    SecurityContext,
    SecurityErrorCode,
    SecurityEvent,
    SessionScope,
    build_security_context,
    make_system_principal,
    make_test_principal,
)
from decision_agent.security.policy import AuthorizationPolicy, DefaultDenyAuthorizationPolicy
from decision_agent.security.provider_policy import (
    DataClassification,
    ProviderPolicy,
    ProviderPolicyError,
    ProviderStage,
    ProviderStagePolicy,
    require_provider_egress,
)
from decision_agent.security.redaction import (
    DeterministicProviderRedactor,
    ProviderRedactor,
    RedactionResult,
    ensure_safe_provider_output,
    sanitize_provider_payload,
    sanitize_provider_text,
)

__all__ = [
    "AuditAction",
    "AuditChainError",
    "AuditComponent",
    "AuditEvent",
    "AuditEventType",
    "AuditOutcome",
    "AuditSink",
    "AuthenticationMethod",
    "AuthorizationPolicy",
    "DataClassification",
    "DataScope",
    "DefaultDenyAuthorizationPolicy",
    "DeterministicProviderRedactor",
    "GovernedChatCompletionClient",
    "GovernedNativeToolCallingModel",
    "GovernedProviderRole",
    "InMemoryAuditSink",
    "JsonlAuditSink",
    "KnowledgeScope",
    "PrincipalType",
    "ProviderGovernance",
    "ProviderPolicy",
    "ProviderPolicyError",
    "ProviderRedactor",
    "ProviderStage",
    "ProviderStagePolicy",
    "RedactionResult",
    "RequestPrincipal",
    "SecurityAuthorizationError",
    "SecurityContext",
    "SecurityErrorCode",
    "SecurityEvent",
    "SessionScope",
    "build_security_context",
    "ensure_safe_provider_output",
    "make_system_principal",
    "make_test_principal",
    "new_audit_event",
    "require_provider_egress",
    "sanitize_provider_payload",
    "sanitize_provider_text",
]
